name: rubika
description: A library to create Rubika bots
version: 0.0.1
homepage: https://github.com/salexhx/rubika

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  http: ^0.13.4
  encrypt: ^5.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
